### ISSUE TITLE
nginx causes conflict with passenger

### ISSUE THREAD

**Issue by graybeal** [ncbo/virtual_appliance#17]
from Patrick Hayes: First time I went to update the installed packages, the installed version of nginx was causing a conflict with passenger and holding back a bunch of other packages.  Solution I found at https://github.com/phusion/passenger/issues/2284 was to uninstall nginx and nginx-filesystem, update the rest of the system, then install nginx-mod-http-passenger (from the epel repo, not the passenger repo) and copy OntoPortal’s nginx config files over.  This appears to have worked, though my ability to test is limited.  Might want to look into updating the virtual appliance to this version before doing the official release.  If there are other things you know of that I might have broken by updating this way, please let me know.

**Comment by alexskr** [comment]
we install mod_passenger for apache from passenger yum repo.  I suspect appliance build was installing nginx from passenger yum repo instead of epel repo since it was a newer version.   Nginx package was pulled from passenger repo which broke yum update. 
This will be naturally solved when we package the next version of the virtual appliance.

Appliance v3.0.1 users should uninstall nginx v1.17 and then install nginx v1.16 from epel repo and mod_passenger package.

**Comment by alexskr** [comment]
fixed in appliance v3.0.2
