### ISSUE TITLE
New appliance (3.2) UI get stuck on "initialize"

### ISSUE THREAD

**Issue by jonquet** [ncbo/virtual_appliance#37]
We have @imadbourouche here at INRAE/Montpellier who recently used the latest release of the appliance. 
Will provide details.

**Comment by alexskr** [comment]
sometimes it can happen when appliance doesn't get IP address from the DHCP.   Would you be able to provide a screen shot of the console of the appliance?

**Comment by imadbourouche** [comment]
yes, here are the screenshots.
Ps:
- the version of ontoportal appliance that i'm using is 3.2.0.
- i can ssh to the virtual machine successfully.

![ssh](https://github.com/ncbo/virtual_appliance/assets/66650181/61d7ddb3-25bf-4522-af56-6cd3b8737179)
![rest_service](https://github.com/ncbo/virtual_appliance/assets/66650181/b774b1e3-9d9e-43fe-b0be-53bfc607ae1b)
![home_page](https://github.com/ncbo/virtual_appliance/assets/66650181/7fa1e9b3-47ad-4e3b-8802-9e46f6c7ea9e)
![ip_address](https://github.com/ncbo/virtual_appliance/assets/66650181/36a5aa1c-ad3b-4a66-935d-90142fd23aba)

**Comment by alexskr** [comment]
when appliance is booted for the very first time it runs [firstboot.rb ](https://github.com/ncbo/virtual_appliance/blob/3.2/utils/bootstrap/firstboot.rb)script which resets secrets so that all deployed appliances have unique api keys and rails secrets.   This script supposed to remove `/srv/ontoportal/bioportal_web_ui/current/public/system/maintenance.html` to disable the maintenance notification.  I am guessing the firstboot script failed to run successfully in your case so maintenance page is not removed.  

I have previously seen this behavior with the appliance when VM couldn't get the IP address so i would need to make firstboot script less brittle. 
In the mean time you can try to manually run this script:
```
touch /srv/ontoportal/firstboot
chown ontoportal:ontoportal /srv/ontoportal/firstboot
```

**Comment by imadbourouche** [comment]
By running the firstboot.rb script it worked now. Thank you.
![ui](https://github.com/ncbo/virtual_appliance/assets/66650181/b844d1e4-107c-4159-b5c5-c930303af7da)

**Comment by alexskr** [comment]
We made a number of fixes to address initialization issues:

1. The script for determines appliance's IP address fails in some edge cases which prevents starting ncbo_cron and unicorn services.   This is addressed by https://github.com/ncbo/virtual_appliance/commit/104cd1f95b6aa2fc423bb737057cbdbe30ff1212

2. firstboot script can fail for VMs that have low number of CPUs/RAM.  This is addressed by   https://github.com/ncbo/virtual_appliance/commit/49f81fb2d91017d2ad9ab63bb5b650456015ff5a
